### ISSUE TITLE
Enhance tree to have folder structure shown

### ISSUE THREAD

**Issue by rythos42** [rtbenfield/vscode-jest-test-adapter#25]
I'm halfway through implementing this, so here's a screenshot.

![image](https://user-images.githubusercontent.com/937640/51949225-915dc980-23e0-11e9-8fd5-5e62c7798eec.png)

I find the straight list of files hard to manage, particularly since it's in Jests order which appears to be somewhat random. Making this list a tree-view on the folder structure would really help it's usability!

**Comment by klis87** [comment]
This is actually how it works for mocha adapter if I remember correctly, I find it a better approach especially for long paths :+1:

**Comment by rtbenfield** [comment]
This is great, @rythos42! I have been wanting to do the same and have not had the time. In fact, the `load_tests_performance` performance branch that I am currently working on is outputting the tests this way as well. I'm going to mark this as something to have in 0.2 so that it stays a high priority.

I was also thinking about adding a user setting to toggle into a grouping by test name without regard to directory structure. The nesting would be done by describe blocks. Describe blocks with the same name would be grouped together across files. My scenario is that I use describe blocks to somewhat mirror the directory structure (though it really resembles the React component hierarchy I have). The full names come up to be something like `FeatureName tests -> ComponentName tests -> SubComponentName tests -> does something correctly`. These tests are still scattered across multiple files, but the hierarchy remains consistent. Because of this, I thought it might be useful to have a way to visualize the tests in this way. What do you all think about that approach? I don't think it would be the default option, but I'm curious if anyone else would find it useful.

**Comment by rythos42** [comment]
Very interesting! But no, I don't think my use-case would find that useful. We barely use describe blocks in my team, tending to let the filename be the "describe" part.

**Comment by rtbenfield** [comment]
Thanks to @rythos42 for resolving this in PR #23!
